name: Scrape Karirhub

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug folder
        run: |
          echo "CURRENT DIR:"
          pwd
          echo "FILES:"
          ls -R

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run scraper (FORCE PATH)
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: |
          echo "RUNNING PYTHON..."
          python ./scraper.py
